### ISSUE TITLE
Add SAGA infrastructure

### ISSUE THREAD

**Issue by ateucher** [ninoxconsulting/PEMprepr#10]
6. I added the bare bones for the function to generate SAGA derived outputs. This is a little complex, but taps into users saga_cmd.exe file. I have it working currently but very fragile. Perhaps we can keep this as working copy and update if time permits. It uses internal dataset and additional utils files. There is an parallel version (https://github.com/bcgov/PEMprepr/blob/master/R/parallel_create_covariates.R, which I think also uses this: https://github.com/bcgov/PEMprepr/blob/master/R/preprocess_dtm.R (to chop large DTM into pieces) and https://github.com/bcgov/PEMprepr/blob/master/R/mosaic_covariates.R (to recombine tiles outputs back into one layer).

_Originally posted by @ateucher in https://github.com/ninoxconsulting/PEMprepr/issues/6#issuecomment-2369394441_

Started in #9

**Comment by ateucher** [comment]
Installation Notes: 

Mac: https://sourceforge.net/p/saga-gis/wiki/Compiling%20SAGA%20on%20Mac%20OS%20X/

Linux: https://sourceforge.net/p/saga-gis/wiki/Binary%20Packages/

**Comment by gcperk** [comment]
@ateucher - if this is a user requirement, how much detail do we need to provide? ie for the user to actually do it. And also how does this impact the test infrastructure? Im not clear how to install these so Github actions can be used/test appropriately?

**Comment by ateucher** [comment]
I think minimal instructions are fine, probably in the documentation for `find_saga_path()` and `check_saga()` (which I think it's probably worth it to export to help users verify/dbug their saga installation.

I can set up the GitHub action; just also requires a bit of work on the `find_saga_path()` and `check_saga()` functions. Is this PR blocking for you, or is it ok to wait a couple of days? I have some ideas, just a bit tight on time this week!

**Comment by gcperk** [comment]
Hey @ateucher - thanks for looking into this. No that's all fine it can wait til next week, I have moved onto the PEMsamplr. I might also make a few changes to the file structure in PEMr package as I work through, but these will only be the file structure so wont ask for review if thats ok. Hope the teaching goes well
