### ISSUE TITLE
check_locations function: insufficient road layer dimensions to reach chosen nearest town. 

### ISSUE THREAD

**Issue by whmacken** [ninoxconsulting/PEMprepr#40]
Currently the road layer is downloaded with the standard buffer dimensions applied early on in PEMprepr
It would be better to download a new road layer for the Samplr portion that uses the AOI plus the chosen towns to create a proper sized bounding box for road layer download.
Also here

**Comment by gcperk** [comment]
Road layers are extracted at two extends. Modelling extent and expanded landscape extent.  A landscape scale AOI is used on line 247 of the [vignette](https://github.com/ninoxconsulting/PEMr/blob/main/vignettes/Setup-new-aoi.Rmd). Does this cover this issue?

**Comment by gcperk** [comment]
moved to here: https://github.com/ninoxconsulting/PEMsamplr/issues/12
